services:

  nginx-proxy:
    build: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/tmp/default.conf
    environment: 
      - DJANGO_SERVER_ADDR=mysite:8000
      - STATIC_SERVER_ADDR=static-fs:8080
    ports:
      - "80:80"
    depends_on:
      - mysite
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:80/health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: /app/start.sh

  beeline:
    build: beeline
    restart: always
    ports: 
      - '8000:8000'
    secrets:
      - db-password
      - django-key
    environment:
      - POSTGRES_DB=example
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - SECRET_KEY_FILE=/run/secrets/django-key
      - DEBUG=1
        # Uncomment this for production
      - DJANGO_SETTINGS_MODULE=beeline.settings.production
        # Comment this for development
        #- DJANGO_SETTINGS_MODULE=mysite.settings.base
    depends_on:
      db:
        condition: service_healthy
    depends_on:
        - static-fs
    healthcheck:
        #test: ["CMD-SHELL", "curl --silent --fail localhost:8000/flask-health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: gunicorn -c gunicorn.config.py -b 0.0.0.0:8000 beeline.wsgi:application
  
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  static-fs:
      image: halverneus/static-file-server:latest
      environment:
          - FOLDER=/var/www
          - DEBUG=true
      expose:
        - 8080
      volumes:
          - ./static-files:/var/www/static
          - ./media-files:/var/www/media

volumes:
  db-data:

secrets:
  db-password:
    file: secrets/db/password.txt
  django-key:
    file: secrets/mysite/secret_key.txt
