"""
Django settings for mysite project production environment.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from .base import *
import environ

# Initialize environment
env = environ.Env()
environ.Env.read_env()

# Read the secret key from file
with open(env("SECRET_KEY_FILE"), 'r') as sk_file:
    SECRET_KEY = sk_file.readline()

print(SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = int(env("DEBUG", default=0))

print(DEBUG)

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# Get DB Password
with open(env("POSTGRES_PASSWORD_FILE"), 'r') as db_pwd:
    DB_PASSWORD = db_pwd.readline()

print(DB_PASSWORD)

DATABASES = {
        'default': {
            "ENGINE": "django.db.backends.postgresql_psycopg2",
            "NAME": env("POSTGRES_DB"),
            "USER": env("POSTGRES_USER"),
            "PASSWORD": "db-mysite-password", #DB_PASSWORD 
            "HOST": env("POSTGRES_HOST"),
            "PORT": env("POSTGRES_PORT"),
        }
    }
