# Generated by Django 4.1.7 on 2023-02-22 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlgorithmResult',
        ),
    ]
